os: windows
language: python

python:
  - 3.9

before_install:
  - choco install make
  - choco install python3
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade setuptools wheel

install:
  - pip install buildozer cython virtualenv

script:
  - git clone https://github.com/kivy/buildozer.git
  - cd buildozer
  - python setup.py install
  - cd ..
  - buildozer init
  - buildozer -v android debug

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "bin/*MathDo.apk"
  skip_cleanup: true
  on:
    tags: true

